export { default as PrevIcon } from './PrevIcon.vue'
export { default as PlayIcon } from './PlayIcon.vue'
export { default as PauseIcon } from './PauseIcon.vue'
export { default as NextIcon } from './NextIcon.vue'
export { default as VolumeIcon } from './VolumeIcon.vue'
